### ISSUE TITLE
publish to luarocks

### ISSUE THREAD

**Issue by flrgh** [Kong/lua-resty-websocket-proxy#11]
- [x] add rockspec file (#13)
- [x] add license (#13)
- [x] make repo public? (probably not 100% necessary if we upload a source rock, but this seems like something we should do)
- [x] audit README and make edits/updates if needed (added note about unstable API status in #13)
- [x] tag

**Comment by thibaultcha** [comment]
Done, #13 is merged and the repository is now public.
